/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GameScenario } from '../types';

export const HISTORICAL_SCENARIOS: GameScenario[] = [
  {
    id: '2026',
    year: 2026,
    title: 'Modern Multipolar Order',
    tagline: 'Digital Disinformation, Geopolitical Flashpoints & Energy Transition',
    description: 'Lead a political movement in an era of polarized party systems, rapid technological transformation, and shifting global alliances.',
    globalTension: 'Elevated',
    dominantIdeologies: ['Liberal Democracy', 'Populism', 'Social Democracy', 'National Conservatism'],
    keyEvents: ['Green Energy Transition', 'Cyber Warfare & AI Regulations', 'NATO Expansion', 'Middle East Stability Accords'],
    economicClimate: 'Post-Inflationary Readjustment & High-Tech Reindustrialization',
    majorPowers: ['United States', 'European Union', 'China', 'United Kingdom', 'Turkey', 'Germany'],
    worldOrderSummary: 'Active contemporary borders with fully mapped 81 Turkish provinces, US Congress electoral college, and German Bundestag dynamics.',
    statusTag: 'PLAYABLE',
  },
  {
    id: '1950',
    year: 1950,
    title: 'Dawn of the Cold War',
    tagline: 'Post-War Reconstruction, Containment Doctrine & Nuclear Shadows',
    description: 'Navigate the emerging ideological rivalry between East and West. Rebuild ruined infrastructure, wage democratic elections, and choose your bloc alignment.',
    globalTension: 'Critical',
    dominantIdeologies: ['Social Market Democracy', 'Classical Conservatism', 'Democratic Socialism', 'Marxist-Leninism'],
    keyEvents: ['Korean Peninsula Outbreak', 'Marshall Plan Allocation', 'Establishment of NATO', 'Decolonization Waves'],
    economicClimate: 'Post-War Reconstruction Boom & Bretton Woods Monetary Order',
    majorPowers: ['United States', 'Soviet Union', 'United Kingdom', 'France', 'Republic of China'],
    worldOrderSummary: 'Bipolar Iron Curtain division, partitioned Germany, Truman Doctrine aid packages, and post-war reconstruction parliaments.',
    statusTag: 'PREVIEW',
  },
  {
    id: '1936',
    year: 1936,
    title: 'The Gathering Storm',
    tagline: 'The Great Depression, Rising Totalitarianism & Rearmament',
    description: 'A world teetering on the precipice. Overcome economic collapse, resist extremist surges, and mobilize parliamentary support before global conflict erupts.',
    globalTension: 'Extreme',
    dominantIdeologies: ['Fascism / Totalitarianism', 'Popular Front Left', 'Constitutional Liberalism', 'Monarchism'],
    keyEvents: ['Remilitarization of the Rhineland', 'Spanish Civil War', 'Anti-Comintern Pact', 'League of Nations Paralysis'],
    economicClimate: 'Protectionist Trade Blocs, Gold Standard Fractures & Industrial Rearmament',
    majorPowers: ['German Reich', 'British Empire', 'Soviet Union', 'United States', 'Empire of Japan', 'Kingdom of Italy'],
    worldOrderSummary: 'Depression-era political polarization, League of Nations breakdown, and frantic military rearmament races across Europe and Asia.',
    statusTag: 'PREVIEW',
  },
  {
    id: '1920',
    year: 1920,
    title: 'The Roaring Twenties & New Orders',
    tagline: 'Treaty of Versailles, League of Nations & Revolutionary Unrest',
    description: 'In the chaotic aftermath of the Great War, reshape national borders, stabilize war debts, grant universal suffrage, and steer nascent republics through turbulent economic waves.',
    globalTension: 'Moderate',
    dominantIdeologies: ['Republicanism', 'Radical Socialism', 'National Liberation', 'Wilsonian Liberalism'],
    keyEvents: ['Treaty of Versailles Implementation', 'Turkish National Movement', 'Polish-Soviet War', 'Rise of Universal Suffrage'],
    economicClimate: 'War Debt Restructuring, Hyperinflation Pressures & Roaring Consumer Speculation',
    majorPowers: ['British Empire', 'French Republic', 'United States', 'Soviet Russia', 'Weimar Republic', 'Empire of Japan'],
    worldOrderSummary: 'Post-imperial collapse, redrawn Middle Eastern and Central European borders, early League of Nations diplomacy, and suffrage reforms.',
    statusTag: 'PREVIEW',
  },
  {
    id: '1914',
    year: 1914,
    title: 'Eve of the Great War',
    tagline: 'Imperial Rivalries, Secret Alliances & Industrial Warfare',
    description: 'Command statecraft among great empires on the edge of the abyss. Balance domestic parliamentarian struggles against imperial defense budgets and mobilization ultimatums.',
    globalTension: 'Extreme',
    dominantIdeologies: ['Imperial Monarchism', 'Classical Liberalism', 'Early Social Democracy', 'Pan-Nationalism'],
    keyEvents: ['July Crisis in Sarajevo', 'Mobilization of the Great Powers', 'Naval Arms Race', 'Entente Cordiale vs. Central Powers'],
    economicClimate: 'First Era of Globalization, Classic Gold Standard & Heavy Industrial Cartels',
    majorPowers: ['German Empire', 'British Empire', 'Russian Empire', 'Austro-Hungarian Empire', 'French Republic', 'Ottoman Empire'],
    worldOrderSummary: 'Interlocking alliance networks, dreadnought battleship arms races, imperial colonial competition, and monarchical diplomacy.',
    statusTag: 'PREVIEW',
  },
];
