const fs = require("fs");
const { kor, prk } = JSON.parse(fs.readFileSync("scripts/korea_theater_regions.json"));

const sectors = [
  // SOUTH KOREA
  {
    id: "KR_seoul",
    name: "Seoul Capital & Incheon Han River Bastion",
    countryId: "KR",
    originalOwnerId: "KR",
    defaultController: "KR",
    terrain: "URBAN",
    isPort: true,
    adjacentRegionIds: ["KR_gyeonggi", "KR_gangwon", "KP_kaesong"],
    strategicValue: 5,
    fortificationLevel: 4,
    infrastructureLevel: 4,
    population: 1800000,
    find: ["Seoul", "Incheon"]
  },
  {
    id: "KR_gyeonggi",
    name: "Gyeonggi-do Frontier & Western Corridor",
    countryId: "KR",
    originalOwnerId: "KR",
    defaultController: "KR",
    terrain: "PLAINS",
    isPort: false,
    adjacentRegionIds: ["KR_seoul", "KR_gangwon", "KR_chungcheong_buk", "KR_chungcheong_nam", "KP_kaesong"],
    strategicValue: 4,
    fortificationLevel: 3,
    infrastructureLevel: 4,
    population: 1500000,
    find: ["Gyeonggi-do"]
  },
  {
    id: "KR_gangwon",
    name: "Gangwon-do East Coast & 38th Parallel Mountains",
    countryId: "KR",
    originalOwnerId: "KR",
    defaultController: "KR",
    terrain: "MOUNTAINS",
    isPort: true,
    adjacentRegionIds: ["KR_gyeonggi", "KR_gyeongsang_buk", "KP_kangwon"],
    strategicValue: 4,
    fortificationLevel: 4,
    infrastructureLevel: 3,
    population: 1100000,
    find: ["Gangwon-do"]
  },
  {
    id: "KR_chungcheong_nam",
    name: "Chungcheongnam-do & Daejeon Rail Hub",
    countryId: "KR",
    originalOwnerId: "KR",
    defaultController: "KR",
    terrain: "PLAINS",
    isPort: true,
    adjacentRegionIds: ["KR_gyeonggi", "KR_chungcheong_buk", "KR_jeolla_buk"],
    strategicValue: 4,
    fortificationLevel: 3,
    infrastructureLevel: 4,
    population: 1600000,
    find: ["Chungcheongnam-do", "Daejeon", "Sejong"]
  },
  {
    id: "KR_chungcheong_buk",
    name: "Chungcheongbuk-do Central Inland Sector",
    countryId: "KR",
    originalOwnerId: "KR",
    defaultController: "KR",
    terrain: "MOUNTAINS",
    isPort: false,
    adjacentRegionIds: ["KR_gyeonggi", "KR_gangwon", "KR_chungcheong_nam", "KR_gyeongsang_buk"],
    strategicValue: 3,
    fortificationLevel: 2,
    infrastructureLevel: 3,
    population: 950000,
    find: ["Chungcheongbuk-do"]
  },
  {
    id: "KR_jeolla_buk",
    name: "Jeollabuk-do & Western Plain",
    countryId: "KR",
    originalOwnerId: "KR",
    defaultController: "KR",
    terrain: "PLAINS",
    isPort: true,
    adjacentRegionIds: ["KR_chungcheong_nam", "KR_jeolla_nam", "KR_gyeongsang_nam"],
    strategicValue: 3,
    fortificationLevel: 2,
    infrastructureLevel: 3,
    population: 1200000,
    find: ["Jeollabuk-do"]
  },
  {
    id: "KR_jeolla_nam",
    name: "Jeollanam-do & Gwangju Southwest Anchor",
    countryId: "KR",
    originalOwnerId: "KR",
    defaultController: "KR",
    terrain: "COAST",
    isPort: true,
    adjacentRegionIds: ["KR_jeolla_buk", "KR_gyeongsang_nam", "KR_jeju"],
    strategicValue: 4,
    fortificationLevel: 3,
    infrastructureLevel: 3,
    population: 1700000,
    find: ["Jeollanam-do", "Gwangju"]
  },
  {
    id: "KR_gyeongsang_buk",
    name: "Gyeongsangbuk-do & Daegu Defensive Perimeter",
    countryId: "KR",
    originalOwnerId: "KR",
    defaultController: "KR",
    terrain: "MOUNTAINS",
    isPort: true,
    adjacentRegionIds: ["KR_gangwon", "KR_chungcheong_buk", "KR_gyeongsang_nam"],
    strategicValue: 5,
    fortificationLevel: 5,
    infrastructureLevel: 4,
    population: 2100000,
    find: ["Gyeongsangbuk-do", "Daegu"]
  },
  {
    id: "KR_gyeongsang_nam",
    name: "Busan Perimeter & Nakdong River Line",
    countryId: "KR",
    originalOwnerId: "KR",
    defaultController: "KR",
    terrain: "COAST",
    isPort: true,
    adjacentRegionIds: ["KR_gyeongsang_buk", "KR_jeolla_nam", "KR_jeolla_buk"],
    strategicValue: 5,
    fortificationLevel: 5,
    infrastructureLevel: 5,
    population: 2500000,
    find: ["Busan", "Gyeongsangnam-do", "Ulsan"]
  },
  {
    id: "KR_jeju",
    name: "Jeju Island Naval & Air Base",
    countryId: "KR",
    originalOwnerId: "KR",
    defaultController: "KR",
    terrain: "COAST",
    isPort: true,
    adjacentRegionIds: ["KR_jeolla_nam"],
    strategicValue: 4,
    fortificationLevel: 3,
    infrastructureLevel: 3,
    population: 300000,
    find: ["Jeju"]
  },

  // NORTH KOREA
  {
    id: "KP_kaesong",
    name: "Kaesong 38th Parallel Gateway",
    countryId: "KP",
    originalOwnerId: "KP",
    defaultController: "KP",
    terrain: "PLAINS",
    isPort: false,
    adjacentRegionIds: ["KR_seoul", "KR_gyeonggi", "KP_hwanghae_nam", "KP_hwanghae_buk"],
    strategicValue: 4,
    fortificationLevel: 4,
    infrastructureLevel: 3,
    population: 250000,
    find: ["Kaesŏng"]
  },
  {
    id: "KP_hwanghae_nam",
    name: "Hwanghae-namdo & Haeju Coast",
    countryId: "KP",
    originalOwnerId: "KP",
    defaultController: "KP",
    terrain: "COAST",
    isPort: true,
    adjacentRegionIds: ["KP_kaesong", "KP_hwanghae_buk", "KP_pyongan_nam"],
    strategicValue: 3,
    fortificationLevel: 3,
    infrastructureLevel: 3,
    population: 950000,
    find: ["Hwanghae-namdo"]
  },
  {
    id: "KP_hwanghae_buk",
    name: "Hwanghae-bukto & Sariwon Corridor",
    countryId: "KP",
    originalOwnerId: "KP",
    defaultController: "KP",
    terrain: "PLAINS",
    isPort: false,
    adjacentRegionIds: ["KP_kaesong", "KP_hwanghae_nam", "KP_pyongyang", "KP_kangwon"],
    strategicValue: 4,
    fortificationLevel: 3,
    infrastructureLevel: 3,
    population: 850000,
    find: ["Hwanghae-bukto"]
  },
  {
    id: "KP_pyongyang",
    name: "Pyongyang Supreme Command Bastion",
    countryId: "KP",
    originalOwnerId: "KP",
    defaultController: "KP",
    terrain: "URBAN",
    isPort: false,
    adjacentRegionIds: ["KP_hwanghae_buk", "KP_pyongan_nam"],
    strategicValue: 5,
    fortificationLevel: 5,
    infrastructureLevel: 4,
    population: 1500000,
    find: ["P'yŏngyang"]
  },
  {
    id: "KP_pyongan_nam",
    name: "Pyongan-namdo & Nampo Naval Port",
    countryId: "KP",
    originalOwnerId: "KP",
    defaultController: "KP",
    terrain: "COAST",
    isPort: true,
    adjacentRegionIds: ["KP_pyongyang", "KP_pyongan_buk", "KP_chagang"],
    strategicValue: 4,
    fortificationLevel: 4,
    infrastructureLevel: 4,
    population: 1400000,
    find: ["P'yŏngan-namdo"]
  },
  {
    id: "KP_pyongan_buk",
    name: "Pyongan-bukto & Sinuiju Yalu River Bridges",
    countryId: "KP",
    originalOwnerId: "KP",
    defaultController: "KP",
    terrain: "PLAINS",
    isPort: true,
    adjacentRegionIds: ["KP_pyongan_nam", "KP_chagang"],
    strategicValue: 5,
    fortificationLevel: 4,
    infrastructureLevel: 4,
    population: 1600000,
    find: ["P'yŏngan-bukto", "Sinŭiju"]
  },
  {
    id: "KP_kangwon",
    name: "Kangwon-do & Wonsan Deepwater Port",
    countryId: "KP",
    originalOwnerId: "KP",
    defaultController: "KP",
    terrain: "MOUNTAINS",
    isPort: true,
    adjacentRegionIds: ["KR_gangwon", "KP_hwanghae_buk", "KP_hamgyong_nam"],
    strategicValue: 5,
    fortificationLevel: 4,
    infrastructureLevel: 3,
    population: 950000,
    find: ["Kangwŏn-do", "Kumgangsan"]
  },
  {
    id: "KP_hamgyong_nam",
    name: "Hamgyong-namdo & Hungnam Heavy Chemical Coast",
    countryId: "KP",
    originalOwnerId: "KP",
    defaultController: "KP",
    terrain: "COAST",
    isPort: true,
    adjacentRegionIds: ["KP_kangwon", "KP_hamgyong_buk", "KP_chagang", "KP_ryanggang"],
    strategicValue: 4,
    fortificationLevel: 3,
    infrastructureLevel: 3,
    population: 1300000,
    find: ["Hamgyŏng-namdo"]
  },
  {
    id: "KP_hamgyong_buk",
    name: "Hamgyong-bukto & Chongjin Steel Port",
    countryId: "KP",
    originalOwnerId: "KP",
    defaultController: "KP",
    terrain: "COAST",
    isPort: true,
    adjacentRegionIds: ["KP_hamgyong_nam", "KP_ryanggang"],
    strategicValue: 4,
    fortificationLevel: 3,
    infrastructureLevel: 3,
    population: 1100000,
    find: ["Hamgyŏng-bukto", "Rasŏn"]
  },
  {
    id: "KP_chagang",
    name: "Chagang-do & Chosin Reservoir Alpine Stronghold",
    countryId: "KP",
    originalOwnerId: "KP",
    defaultController: "KP",
    terrain: "MOUNTAINS",
    isPort: false,
    adjacentRegionIds: ["KP_pyongan_buk", "KP_pyongan_nam", "KP_hamgyong_nam", "KP_ryanggang"],
    strategicValue: 4,
    fortificationLevel: 4,
    infrastructureLevel: 2,
    population: 600000,
    find: ["Chagang-do"]
  },
  {
    id: "KP_ryanggang",
    name: "Ryanggang & Mount Paektu Border Redoubt",
    countryId: "KP",
    originalOwnerId: "KP",
    defaultController: "KP",
    terrain: "MOUNTAINS",
    isPort: false,
    adjacentRegionIds: ["KP_chagang", "KP_hamgyong_nam", "KP_hamgyong_buk"],
    strategicValue: 3,
    fortificationLevel: 3,
    infrastructureLevel: 2,
    population: 450000,
    find: ["Ryanggang"]
  }
];

const allRegions = sectors.map(sec => {
  const matchFeatures = [...kor, ...prk].filter(f => sec.find.includes(f.name));
  const mainFeat = matchFeatures[0];
  return {
    id: sec.id,
    name: sec.name,
    countryId: sec.countryId,
    originalOwnerId: sec.originalOwnerId,
    defaultController: sec.defaultController,
    center: mainFeat.center,
    polygon: mainFeat.polygon,
    terrain: sec.terrain,
    isPort: sec.isPort,
    adjacentRegionIds: sec.adjacentRegionIds,
    strategicValue: sec.strategicValue,
    fortificationLevel: sec.fortificationLevel,
    infrastructureLevel: sec.infrastructureLevel,
    population: sec.population
  };
});

console.log("Total Korean War Theater Sectors:", allRegions.length);
fs.writeFileSync("scripts/formatted_korean_theater.json", JSON.stringify(allRegions, null, 2));
